"""Guard: every documented API route must exist on the app (catches accidental deletions during refactors)."""
import os, sys; sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend")); os.environ.setdefault("FILMOCITY_ROOT", "/tmp/filmocity_routes_test")
import server
paths = {r.path for r in server.app.routes if hasattr(r, "path")}
required = ["/api/project", "/api/media/import", "/api/media/upload", "/api/media/file/{mid}", "/api/events", "/api/annotate", "/api/snapshot", "/api/snapshots", "/api/snapshots/restore", "/api/render", "/api/render/{jid}", "/api/render_command", "/api/jobs", "/api/encoders", "/api/settings", "/api/proposals", "/api/proposals/{pid}/{iid}/{decision}", "/api/captions/import", "/api/captions/export", "/api/captions/auto", "/api/export/fcpxml", "/api/export/otio", "/api/import/fcpxml", "/api/frame", "/api/fonts", "/api/media/relink", "/api/media/status", "/api/fs", "/api/media/subclip", "/api/audio/measure", "/api/session/summary", "/api/training/export", "/api/projects", "/api/projects/new", "/api/projects/open", "/api/projects/save_as", "/api/projects/collect", "/api/media/scenes", "/api/transcript", "/api/effects", "/api/stabilize", "/api/luts", "/api/templates", "/api/presets/{kind}", "/api/media/synthetic", "/api/audio/peak", "/api/render_replace", "/api/export/edl", "/api/captions/export_vtt", "/api/app_events", "/api/audio/sync", "/api/markers/export", "/api/media/interpret", "/api/media/extract_audio", "/api/media/breakout", "/api/render_all", "/api/advisor/score", "/api/advisor/train", "/api/advisor/report", "/api/media/probe", "/api/audio/remix", "/api/diagnostics", "/api/projects/sample", "/api/backups", "/api/backups/restore", "/api/render/{jid}/cancel", "/api/snapshots/get", "/api/version", "/api/openapi.json", "/api/docs", "/api/luts/file", "/api/undo", "/api/redo", "/api/undo/stack", "/api/render/segments", "/api/render/preview", "/api/media/input_transform", "/api/graphics/split_words", "/api/audio/beats", "/api/media/sfx", "/api/media/path", "/api/fonts/upload", "/api/media/import_sequence", "/api/templates/preview", "/api/recipes/reel", "/api/audio/silences", "/api/sequences/variants", "/api/sequence/describe", "/api/renders/manifest", "/api/markers/note", "/api/recipes/cover", "/api/recipes/explainer", "/api/cache", "/api/cache/clear", "/api/recipes/talking_head", "/api/audio/duck_all", "/api/install/whisper", "/review/{name}", "/ws"]
required.extend(["/api/projects/recovery", "/api/project/state"])
missing = [p for p in required if p not in paths]
assert not missing, f"missing routes: {missing}"
print(f"OK routes: {len(required)} required, {len(paths)} present")
