const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {fixture,plain,until,saved,context,event}=require('./helpers/clip-attributes-workflow-fixture.cjs');
test('multiple copied clips have explicit named donor choices and six safe category defaults',()=>{const f=fixture();f.copy(['a','c']);f.scope.S.sel=new Set(['b']);f.open();const d=f.dialog();assert.equal(d.donor.children.length,2);assert.match(d.donor.children[0].textContent,/Donor A.*6\.000000/);assert.match(d.donor.children[1].textContent,/Donor C/);assert.equal(d.donor.value,'0');assert.equal(d.animation.checked,true);assert.equal(d.timing.value,'seconds');assert.deepEqual(f.choices().groups,['motion','color','video_effects','audio_effects','audio_gain','audio_fades']);assert.equal(d.groups.length,9);assert.equal(f.requests.length,0);});
test('copy freezes donor source identity and format without derivative payloads',async()=>{const f=fixture();Object.assign(f.project.media.m,{transcript:{words:['private']},wave:'/wave.png',proxy:'/proxy.mp4',source_relink_basis:{stamp:{mtime_ns:'1700000000000000123'}}});f.copy(['a','c']);f.scope.S.sel=new Set(['b']);f.open();f.dialog().donor.value='1';f.dialog().donor.onchange();const r=await f.review(),body=f.body();assert.equal(body.donor.clip.id,'c');assert.equal(body.donor.sequence.id,'s1');assert.equal(body.donor.sequence.fps,30);assert.equal(body.donor.media.transcript,undefined);assert.equal(body.donor.media.wave,undefined);assert.equal(body.donor.media.proxy,undefined);assert.equal(body.donor.media.source_relink_basis.stamp.mtime_ns,'1700000000000000123');assert.equal(r.donor.clip.id,'c');});
test('read-only review displays donor/target windows, formats, categories, curves and warnings',async()=>{const f=fixture(),before=plain(f.project),r=await f.review();assert.deepEqual(plain(f.project),before);assert.equal(f.requests.length,1);assert.match(f.dialog().output.textContent,/600×300.*30 fps/);assert.match(f.dialog().output.textContent,/Timeline 8\.000000–11\.000000/);assert.match(f.dialog().output.textContent,/fade tail extends/);assert.match(f.dialog().output.textContent,/Curves: transform.x/);assert.equal(f.dialog().apply.disabled,false);assert.deepEqual(f.body().donor,r.donor);});
test('locked mixed selection and every Recovery/loading guard refuse before opening or mutating',()=>{for(const mode of ['locked','saveError','recoveryRequired','gesture','switching','commandPending']){const f=fixture();if(mode==='locked')f.tr.locked=true;else if(mode==='saveError')f.scope.projectSaveState().error='Unconfirmed save';else f.scope.S[mode]=mode==='gesture'?{}:true;const before=plain(f.project);assert.equal(f.open(),false);assert.deepEqual(plain(f.project),before);assert.equal(f.requests.length,0);assert.equal(f.scope.S.hist.length,0);}});
test('pending save completes before review and the revised owner is sent',async()=>{const f=fixture();f.scope.applyOps([{op:'set',path:'/name',value:'Pending'}],'name','name');f.open();const p=f.dialog().review.click();assert.equal(f.requests.length,1);f.requests[0].resolve(saved('r1'));await until(()=>f.requests.length===2);assert.equal(f.body(1)._context.revision,'r1');f.reply(1,f.report());await p;assert.equal(f.dialog().apply.disabled,false);});
test('Escape while waiting on save prevents review dispatch and restores focus',async()=>{const f=fixture(),origin=f.scope.$('#origin');origin.focus();f.scope.applyOps([{op:'set',path:'/name',value:'Pending'}],'name','name');f.open();const p=f.dialog().review.click();f.window.emit('keydown',event({key:'Escape'}));f.requests[0].resolve(saved('r1'));await p;assert.equal(f.requests.length,1);assert.equal(f.dialog().box.classList.contains('open'),false);f.flushTimers();assert.equal(f.document.activeElement,origin);});
test('late reviews retire after target, selection, clipboard, sequence or project changes',async()=>{for(const change of [f=>f.scope.S.sel.clear(),f=>f.clips[1].out++,f=>f.tr.locked=true,f=>{f.copy(['c']);f.scope.S.sel=new Set(['b']);},f=>f.scope.S.seq=f.project.sequences[1],f=>f.scope.S.context=context('r0','other')]){const f=fixture();f.open();const p=f.dialog().review.click();await until(()=>f.requests.length===1);const report=f.report();change(f);const before=plain(f.scope.S.proj);f.reply(0,report);assert.equal(await p,false);assert.equal(f.dialog().apply.disabled,true);assert.deepEqual(plain(f.scope.S.proj),before);assert.equal(Boolean(f.scope.projectSaveState().error),false);}});
test('choice changes invalidate reviews including changed controls without a dispatched DOM event',async()=>{for(const notify of [true,false]){const f=fixture();await f.review();f.dialog().timing.value='scale';if(notify)f.dialog().timing.onchange();await f.dialog().apply.click();assert.equal(f.requests.length,1);assert.equal(f.dialog().apply.disabled,true);}});
test('changing animation values-only state is explicit and cannot submit an old review',async()=>{const f=fixture();await f.review();f.dialog().animation.checked=false;f.dialog().animation.onchange();assert.match(f.scope.$('#paAnimationNotice').textContent,/target keyframes are kept/);assert.equal(f.dialog().apply.disabled,true);const r=await f.review();assert.equal(r.settings.include_animation,false);assert.match(f.dialog().output.textContent,/can override/);});
test('empty category selection refuses before transport and can be corrected',async()=>{const f=fixture();f.open();for(const input of f.dialog().groups)input.checked=false;f.dialog().groups[0].onchange();assert.equal(await f.dialog().review.click(),false);assert.equal(f.requests.length,0);assert.match(f.dialog().output.textContent,/at least one/);f.dialog().groups[0].checked=true;f.dialog().groups[0].onchange();await f.review();assert.equal(f.dialog().apply.disabled,false);});
test('refused and malformed reviews never enable Apply or hide actionable guidance',async()=>{const f=fixture(),message='Track Matte needs explicit dependency mapping.';await f.review({ok:false,issues:[{code:'dependency',severity:'error',message}]});const text=f.dialog().output.textContent;assert.ok(text.includes(message));await f.dialog().apply.click();assert.equal(f.dialog().output.textContent,text);assert.equal(f.requests.length,1);for(const extra of [{fingerprint:'bad'},{context:context('other')},{donor:{}},{settings:{groups:[],timing:'seconds',include_animation:true}}]){const g=fixture();await g.review(extra);assert.equal(g.dialog().apply.disabled,true);assert.equal(Boolean(g.scope.projectSaveState().error),false);}});
test('exact reviewed Apply has no optimistic mutation and reloads the canonical saved target',async()=>{const f=fixture(),r=await f.review(),before=plain(f.project),p=f.dialog().apply.click();await until(()=>f.requests.length===2);assert.deepEqual(plain(f.project),before);assert.equal(f.body(1).fingerprint,r.fingerprint);assert.deepEqual(f.body(1).donor,r.donor);assert.deepEqual(f.body(1)._context,r.context);const result=await f.ack(p,r);assert.equal(result.ok,true);assert.equal(f.scope.S.seq.tracks[0].clips[1].transform.canonical,true);assert.deepEqual([...f.scope.S.sel],['b']);assert.equal(f.requests.length,3);});
test('no-op Apply accepts unchanged context and reloads only the local history baseline',async()=>{const f=fixture(),r=await f.review({changed:false}),before=plain(f.project),p=f.dialog().apply.click();await until(()=>f.requests.length===2);assert.equal(f.scope.S.hist.length,0);const result=await f.ack(p,r);assert.equal(result.changed,false);assert.equal(result.context.revision,r.context.revision);assert.deepEqual(plain(f.scope.S.proj),before);assert.equal(f.scope.S.hist.length,1);assert.deepEqual(JSON.parse(f.scope.S.hist[0]),before);});
test('Cancel after dispatch does not reject a valid saved receipt or resend',async()=>{const f=fixture(),r=await f.review(),p=f.dialog().apply.click();await until(()=>f.requests.length===2);f.dialog().cancel.click();assert.equal((await f.ack(p,r)).ok,true);assert.equal(Boolean(f.scope.projectSaveState().error),false);assert.equal(f.requests.length,3);});
test('newer selection, source clipboard and navigation survive saved acknowledgment',async()=>{for(const mode of ['selection','clipboard','sequence']){const f=fixture(),r=await f.review(),p=f.dialog().apply.click();await until(()=>f.requests.length===2);if(mode==='selection')f.scope.S.sel=new Set(['c']);if(mode==='clipboard'){f.copy(['c']);f.scope.S.sel=new Set(['c']);}if(mode==='sequence'){f.scope.S.seq=f.project.sequences[1];f.scope.S.seqId='s2';f.scope.S.sel.clear();}await f.ack(p,r);if(mode==='sequence')assert.equal(f.scope.S.seqId,'s2');else assert.deepEqual([...f.scope.S.sel],['c']);}});
test('foreign project during Apply never reloads or mutates the new project',async()=>{const f=fixture(),r=await f.review(),p=f.dialog().apply.click();await until(()=>f.requests.length===2);f.scope.S.proj=plain(f.project);f.scope.S.context=context('foreign','other');const before=plain(f.scope.S.proj);f.reply(1,f.replyAttributes(r));assert.equal(await p,false);assert.equal(f.requests.length,2);assert.deepEqual(plain(f.scope.S.proj),before);});
test('unknown or mismatched Apply replies enter Recovery with no replay',async()=>{for(const kind of ['network','summary','ids']){const f=fixture(),r=await f.review(),p=f.dialog().apply.click();await until(()=>f.requests.length===2);if(kind==='network')f.requests[1].reject(Error('lost possible saved reply'));else{const reply=f.replyAttributes(r);if(kind==='summary')reply.summary.message='Unreviewed change';else reply.changed_clip_ids=['other'];f.reply(1,reply);}assert.equal(await p,false);assert.ok(f.scope.projectSaveState().error);await f.dialog().apply.click();await f.dialog().review.click();assert.equal(f.requests.length,2);}});
test('known conflict keeps read-only fresh review available without Recovery',async()=>{const f=fixture();await f.review();const p=f.dialog().apply.click();await until(()=>f.requests.length===2);f.reply(1,{detail:'Target changed'},409);assert.equal(await p,false);assert.equal(Boolean(f.scope.projectSaveState().error),false);assert.equal(f.dialog().review.disabled,false);});
test('reopened controls and repeated pending actions cannot dispatch twice',async()=>{const f=fixture();f.open();const old=f.dialog().review.onclick;f.dialog().cancel.click();f.open();assert.equal(await old(),false);const p=f.dialog().review.click();await f.dialog().review.click();await until(()=>f.requests.length===1);f.reply(0,f.report());await p;const a=f.dialog().apply.click();await f.dialog().apply.click();await until(()=>f.requests.length===2);await f.ack(a,f.dialog().box.attributeOwner.review.report);assert.equal(f.requests.length,3);});
test('Apply pauses playback without committing pending trim and final dispatch rechecks cancellation',async()=>{const f=fixture(),r=await f.review(),calls=[];f.scope.S.playing=true;f.scope.togglePlay=(...args)=>{calls.push(plain(args));f.scope.S.playing=false;};const p=f.dialog().apply.click();await until(()=>f.requests.length===2);assert.deepEqual(calls,[[false,{commitTrim:false}]]);await f.ack(p,r);const g=fixture();await g.review();const request=g.scope.workflowRequest;g.scope.workflowRequest=(fn,basis)=>request(c=>{g.dialog().cancel.click();return fn(c);},basis);assert.equal(await g.dialog().apply.click(),false);assert.equal(g.requests.length,1);});
test('donor and review envelope mutation cannot alter an accepted plan',async()=>{const f=fixture(),r=await f.review();r.donor.clip.transform.x=900;await f.dialog().apply.click();assert.equal(f.requests.length,1);const g=fixture(),owner=g.open();owner.donors[0].bundle.clip.out=50;assert.equal(await g.dialog().review.click(),false);assert.equal(g.requests.length,0);});
test('actual document keeps unique IDs, accessible fields and explicit timing labels',()=>{const html=fs.readFileSync('frontend/index.html','utf8'),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.match(html,/id="dlgPasteAttributes"[^>]+aria-labelledby="paTitle"/);assert.match(html,/<label for="paDonor">/);assert.match(html,/Keep copied seconds/);assert.match(html,/Scale to target duration/);assert.match(html,/id="paReview"[^>]+aria-live="polite"/);});

test('inconsistent reviewed durations, scale ratios or changed IDs refuse before Apply',async()=>{for(const mutate of [r=>r.summary.donor.duration++,r=>r.summary.targets[0].duration++,r=>r.summary.targets[0].ratio=3,r=>r.summary.targets[0].changed=false]){const f=fixture();f.open();const p=f.dialog().review.click();await until(()=>f.requests.length===1);const r=f.report();mutate(r);f.reply(0,r);assert.equal(await p,false);assert.equal(f.dialog().apply.disabled,true);assert.equal(f.requests.length,1);assert.equal(Boolean(f.scope.projectSaveState().error),false);}});

test('review retains copied human name and format after donor deletion and target format change',async()=>{const f=fixture();delete f.clips[0].name;f.project.media.m.name='Interview camera';f.copy(['a']);f.tr.clips=f.tr.clips.filter(c=>c.id!=='a');f.seq.width=1280;f.seq.height=720;f.seq.fps=25;f.scope.S.sel=new Set(['b']);const r=await f.review();assert.equal(r.donor.clip.id,'a');assert.equal(r.donor.sequence.width,600);assert.equal(r.donor.sequence.fps,30);assert.match(f.dialog().output.textContent,/Donor: Interview camera \[a\]/);assert.match(f.dialog().output.textContent,/formats differ/);assert.match(f.dialog().output.textContent,/1280×720.*25 fps/);assert.equal(f.dialog().apply.disabled,false);});
test('optional changed count must agree and live dependency warnings stay literal',async()=>{const f=fixture();f.open();const p=f.dialog().review.click();await until(()=>f.requests.length===1);const r=f.report();r.summary.warnings.push('Track Matte uses the current live source track in this sequence; its content is not copied or frozen.');assert.equal(r.summary.changed_count,undefined);f.reply(0,r);await p;assert.match(f.dialog().output.textContent,/current live source track.*not copied or frozen/);assert.equal(f.dialog().apply.disabled,false);const g=fixture();g.open();const q=g.dialog().review.click();await until(()=>g.requests.length===1);const bad=g.report();bad.summary.changed_count=99;g.reply(0,bad);assert.equal(await q,false);assert.equal(g.dialog().apply.disabled,true);});

test('Scale review uses actual held, reverse and ramp duration without changing source clocks',async()=>{for(const settings of [{in_:1,out:8,hold:true},{in_:0,out:4,reverse:true},{in_:0,out:4,time_remap:[{t:0,v:1},{t:4,v:2}]}]){const f=fixture();Object.assign(f.clips[1],settings);const before=plain(f.clips[1]);f.open();f.dialog().timing.value='scale';f.dialog().timing.onchange();const r=await f.review();assert.equal(r.summary.targets[0].duration,f.scope.clipDur(f.clips[1]));assert.equal(r.summary.targets[0].ratio,f.scope.clipDur(f.clips[1])/6);assert.deepEqual(plain(f.clips[1]),before);assert.equal(f.dialog().apply.disabled,false);}});
