const test=require('node:test'),assert=require('node:assert/strict');
const {fixture,plain,until,saved,context}=require('./helpers/recipe-workflow-fixture.cjs');
test('recipe queues immutable ordered sources and exact settings without modifying project',async()=>{
 for(const mode of ['reel','talking_head']){const f=fixture(),before=plain(f.project),choices=f.choices(mode),pending=f.scope.startRecipeTask(mode,choices);await until(()=>f.requests.length===1);assert.match(f.requests[0].url,new RegExp('/recipes/'+mode+'$'));assert.match(f.body().request_id,/^[a-f0-9]{32}$/);assert.equal(f.body().sequence,'s1');if(mode==='reel'){assert.deepEqual(f.body().shots,['n','m']);assert.equal(f.body().music,null);assert.equal(f.body().canvas,'portrait');}else{assert.equal(f.body().clip_id,'a');assert.deepEqual(f.body().broll,['n']);}choices.target=50;choices.broll?.push('m');f.reply(0,f.queued());await pending;assert.deepEqual(plain(f.project),before);assert.equal(f.opened(),1);}
});
test('pending saves flush before queue and owner changes during flush reject',async()=>{
 for(const mode of ['good','selection','bin','source','brand','sequence','lock']){const f=fixture();f.scope.applyOps([{op:'set_clip',sequence:'s1',track:'v1',clip:{id:'a',note:'pending'}}],'note','note');const pending=f.scope.startRecipeTask('talking_head',f.choices('talking_head'));if(mode==='selection')f.scope.S.sel.clear();if(mode==='bin')f.scope.S.binSel=new Set(['m','n']);if(mode==='source')f.project.media.n.path='/changed';if(mode==='brand')f.project.brand={font:'changed'};if(mode==='sequence')f.scope.S.seq=f.project.sequences[1];if(mode==='lock')f.tr.locked=true;f.requests[0].resolve(saved('r1'));if(mode==='good'){await until(()=>f.requests.length===2);assert.equal(f.body(1)._context.revision,'r1');f.reply(1,f.queued());await pending;}else{await assert.rejects(pending,/changed/);assert.equal(f.requests.length,1,mode);}}
});
test('Talking Head rejects held, nested, disabled, locked or ambiguous targets',()=>{
 for(const mode of ['hold','nested','disabled','locked','multiple','missing']){const f=fixture(),c=f.tr.clips[0];if(mode==='hold')c.hold=true;if(mode==='nested')c.sequence_id='s2';if(mode==='disabled')c.enabled=false;if(mode==='locked')f.tr.locked=true;if(mode==='multiple')f.scope.S.sel.add('b');if(mode==='missing')f.scope.S.sel=new Set(['missing']);if(mode==='unlinked')c.audio.linked=false;assert.throws(()=>f.scope.captureRecipeTargets('talking_head'),/Select|held|Enable|unlock/);assert.equal(f.requests.length,0);}
});
test('bounded finite choices prevent negative/infinite recipes and fractional subframe punch loops',async()=>{
 for(const [mode,patch] of [['reel',{target:Infinity}],['reel',{target:0}],['reel',{target:601}],['reel',{name:''}],['reel',{rhythm:'onsets',music:null}],['reel',{framing:'unknown'}],['talking_head',{punch_every:-1}],['talking_head',{punch_every:.001}],['talking_head',{punch_every:Infinity}],['talking_head',{min_gap:-1}],['talking_head',{captions:'yes'}]]){const f=fixture();await assert.rejects(f.scope.startRecipeTask(mode,{...f.choices(mode),...patch}));assert.equal(f.requests.length,0,JSON.stringify(patch));}
});
test('audio-only Talking Head can disable punch-ins; reverse and ramp source clocks reach canonical planner',async()=>{
 for(const mode of ['audio','reverse','ramp']){const f=fixture(),c=f.tr.clips[0],choices=f.choices('talking_head');if(mode==='audio'){f.tr.kind='audio';f.project.media.m.has_video=false;choices.punch_every=0;}if(mode==='reverse')c.reverse=true;if(mode==='ramp')c.time_remap=[{t:0,v:.5},{t:3,v:2}];const pending=f.scope.startRecipeTask('talking_head',choices);await until(()=>f.requests.length===1);assert.equal(f.body().in,undefined);assert.equal(f.body().punch_every,mode==='audio'?0:3);f.reply(0,f.queued());await pending;}
});
test('late A-to-B queue response never mutates or opens foreign Tasks',async()=>{
 const f=fixture(),before=plain(f.project),pending=f.scope.startRecipeTask('reel',f.choices());await until(()=>f.requests.length===1);const queued=f.queued(),other=plain(f.project);f.scope.S.proj=other;f.scope.S.seq=other.sequences[0];f.scope.S.context=context('r0','other');f.reply(0,queued);await pending;assert.deepEqual(other,before);assert.equal(f.opened(),0);assert.equal(f.requests.length,1);
});
test('uncertain queue results never retry or mark editable project as Recovery',async()=>{
 const f=fixture(),pending=f.scope.startRecipeTask('reel',f.choices());await until(()=>f.requests.length===1);f.requests[0].reject(Error('lost'));await assert.rejects(pending,/Check Tasks/);assert.equal(!!f.scope.projectSaveState().error,false);assert.equal(f.requests.length,1);
});
test('recipe polling only reviews ready owned tasks and refuses failure or canceled choices',async()=>{
 for(const mode of ['ready','error','cancel']){const f=fixture(),queued=await f.queue();let current=true;const pending=f.scope.waitRecipeTask(queued,{isCurrent:()=>current});await until(()=>f.requests.length===2);if(mode==='cancel')current=false;f.reply(1,f.catalog(mode==='error'?'error':'ready'));if(mode==='ready'){await until(()=>f.requests.length===3);f.reply(2,f.result());assert.equal((await pending).result.mode,'reel');}else{await assert.rejects(pending,/No reliable onsets|changed/);assert.equal(f.requests.length,2);}}
});
test('review verifies version, mode, owner, precise positions and full plan contract',async()=>{
 for(const mode of ['version','task','scope','context','mode','achieved','cut','range','fields']){const f=fixture();await assert.rejects(f.review('reel',r=>{if(mode==='version')r.result.version=2;if(mode==='task')r.task.kind='analysis';if(mode==='scope')r.result.sequence='other';if(mode==='context')r.context=context('r1');if(mode==='mode')r.plan.summary.mode='talking_head';if(mode==='achieved')r.plan.summary.achieved='15';if(mode==='cut')r.plan.summary.cuts=[-1];if(mode==='range')r.plan.summary.ranges=[[3,2]];if(mode==='fields')delete r.plan.summary.affected_fields;}),/confirmed|incomplete/);}
});
test('review rejects source, target and project changes across await',async()=>{
 for(const mode of ['source','target','project','brand']){const f=fixture(),pending=f.scope.reviewRecipeTask('recipe-task');await until(()=>f.requests.length===1);const result=f.result();if(mode==='source')f.project.media.n.path='/changed';if(mode==='target')f.tr.clips[0].start++;if(mode==='project')f.scope.S.proj=plain(f.project);if(mode==='brand')f.project.brand={text:'changed'};f.reply(0,result);await assert.rejects(pending,/changed/);}
});
test('Apply requires original unchanged review and bound target/source/brand state',async()=>{
 for(const mode of ['copy','fingerprint','plan','source','target','brand','lock']){const f=fixture(),reviewed=await f.review();let result=reviewed;if(mode==='copy')result=plain(reviewed);if(mode==='fingerprint')reviewed.plan.fingerprint='forged';if(mode==='plan')reviewed.plan.summary.achieved++;if(mode==='source')f.project.media.m.path='/changed';if(mode==='target')f.tr.clips[0].start++;if(mode==='brand')f.project.brand={font:'changed'};if(mode==='lock')f.tr.locked=true;await assert.rejects(f.scope.applyRecipeTask('recipe-task',result),/changed/);assert.equal(f.requests.length,1);}
});
test('Reel Apply is fingerprint-only, pauses without Trim commit and selects server-created sequence after reload',async()=>{
 const f=fixture(),reviewed=await f.review(),before=plain(f.project),stops=[];f.scope.S.playing=true;f.scope.togglePlay=(on,options)=>{stops.push({on,options:plain(options)});f.scope.S.playing=on;};const pending=f.scope.applyRecipeTask('recipe-task',reviewed);await until(()=>f.requests.length===2);assert.equal(f.body(1).fingerprint,'recipe-fingerprint');assert.equal(f.body(1).ops,undefined);assert.deepEqual(plain(f.project),before);assert.deepEqual(stops,[{on:false,options:{commitTrim:false}}]);await f.applyComplete(pending,1);assert.equal(f.scope.S.seq.id,'new-reel');assert.deepEqual(plain(f.scope.S.proj.sequences.slice(0,2)),before.sequences);
});
test('fresh Tasks review does not depend on selection; final dispatch still checks optional dialog ownership',async()=>{
 const f=fixture(),reviewed=await f.review('talking_head');f.scope.S.sel.clear();f.scope.S.binSel.clear();const pending=f.scope.applyRecipeTask('recipe-task',reviewed);await until(()=>f.requests.length===2);await f.applyComplete(pending,1,'talking_head');
 const g=fixture(),r=await g.review(),original=g.scope.workflowRequest;let active=true;g.scope.workflowRequest=(send,basis)=>original(context=>{active=false;return send(context);},basis);await assert.rejects(g.scope.applyRecipeTask('recipe-task',r,{isCurrent:()=>active}),/changed/);assert.equal(g.requests.length,1);assert.equal(!!g.scope.projectSaveState().error,false);
});
test('uncertain Apply enters Recovery once while definite conflict remains editable',async()=>{
 for(const mode of ['lost','conflict']){const f=fixture(),reviewed=await f.review(),pending=f.scope.applyRecipeTask('recipe-task',reviewed);await until(()=>f.requests.length===2);if(mode==='lost')f.requests[1].reject(Error('lost'));else f.reply(1,{detail:'Source changed'},409);await assert.rejects(pending);assert.equal(!!f.scope.projectSaveState().error,mode==='lost');assert.equal(f.requests.length,2);}
});
test('Talking Head dialog has explicit options and Cancel never submits',()=>{
 const f=fixture();f.open('talking_head');assert.equal(f.requests.length,0);assert.equal(f.scope.$('#thPunch').value,3);assert.equal(f.scope.$('#thBroll').checked,true);f.dialog('talking_head').cancel.onclick();assert.equal(f.requests.length,0);assert.equal(f.dialog('talking_head').box.classList.contains('open'),false);
});
test('Reel loads literal choices with no automatic music and defaults to a separate portrait sequence',async()=>{
 const f=fixture();await f.open('reel');assert.equal(f.requests.length,0);assert.equal(f.scope.$('#reelMusic').value,'');assert.equal(f.scope.$('#reelCanvas').value,'portrait');assert.equal(f.scope.$('#reelRhythm').value,'even');assert.equal(f.scope.$('#reelFraming').value,'auto');assert.equal(f.scope.$('#reelName').value,'New Reel');assert.ok(f.scope.$('#reelMusic').children.some(item=>item.textContent==='<literal music>'));assert.ok(f.scope.$('#reelMusic').children.every(item=>!Object.hasOwn(item,'innerHTML')));assert.match(f.dialog('reel').output.textContent,/new sequence/);
});
test('async Reel catalog load cannot reopen canceled controls or install after project/bin changes',async()=>{
 for(const mode of ['cancel','project','bin','reopen']){const f=fixture();delete f.scope.S.luts;delete f.scope.S.capPresets;const pending=f.open('reel');assert.equal(f.requests.length,2);if(mode==='cancel')f.dialog('reel').cancel.onclick();if(mode==='project')f.scope.S.proj=plain(f.project);if(mode==='bin')f.scope.S.binSel.clear();let second=null;if(mode==='reopen'){f.scope.S.luts=[];f.scope.S.capPresets={};second=f.open('reel');await second;}f.reply(0,[{path:'/late',name:'Late choice'}]);f.reply(1,{'Late style':{}});await pending;assert.ok(!f.scope.$('#reelLook').children.some(item=>item.value==='/late'));assert.equal(f.requests.length,2);if(mode==='cancel')assert.equal(f.dialog('reel').box.classList.contains('open'),false);}
});
test('both dialogs require explicit review followed by a second Apply action',async()=>{
 for(const mode of ['reel','talking_head']){const f=fixture();await f.open(mode);const before=plain(f.project);await f.prepare(mode);assert.equal(f.requests.length,3);assert.deepEqual(plain(f.project),before);assert.match(f.dialog(mode).output.textContent,/1.123456 s/);assert.match(f.dialog(mode).output.textContent,/transform.scale, afx_stack/);assert.match(f.dialog(mode).button.textContent,/reviewed/);const pending=f.dialog(mode).button.onclick();await until(()=>f.requests.length===4);await f.applyComplete(pending,3,mode);assert.equal(f.dialog(mode).box.classList.contains('open'),false);}
});
test('cancel/reopen/settings/selection/locks during queue wait cannot trigger automatic review or Apply',async()=>{
 for(const mode of ['cancel','reopen','settings','selection','lock']){const f=fixture();await f.open('talking_head');const pending=f.dialog('talking_head').button.onclick();await until(()=>f.requests.length===1);if(mode==='cancel')f.dialog('talking_head').cancel.onclick();if(mode==='reopen')f.open('talking_head');if(mode==='settings'){f.scope.$('#thPunch').value=0;f.dialog('talking_head').box.oninput();}if(mode==='selection')f.scope.S.sel.clear();if(mode==='lock')f.tr.locked=true;f.reply(0,f.queued());await pending;assert.equal(f.requests.length,1,mode);}
});
test('reviewed settings changes clear review and require preparing a fresh plan',async()=>{
 const f=fixture();await f.open('reel');await f.prepare();f.scope.$('#reelLen').value=20;f.dialog('reel').box.onchange();assert.equal(f.dialog('reel').button.textContent,'Prepare recipe');f.scope.$('#reelLen').value='';await f.dialog('reel').button.onclick();assert.equal(f.requests.length,3);assert.match(f.dialog('reel').output.textContent,/finite/);
});
test('no-op recipe disables Apply and post-dispatch Cancel does not retract submitted mutation',async()=>{
 const f=fixture();f.open('talking_head');await f.prepare('talking_head',r=>{r.plan.ops=[];});assert.equal(f.dialog('talking_head').button.disabled,true);assert.match(f.dialog('talking_head').output.textContent,/No changes/);
 const g=fixture();await g.open('reel');await g.prepare();const pending=g.dialog('reel').button.onclick();await until(()=>g.requests.length===4);g.dialog('reel').cancel.onclick();await g.applyComplete(pending,3);assert.equal(g.dialog('reel').box.classList.contains('open'),false);assert.equal(g.scope.S.seq.id,'new-reel');assert.ok(!g.messages.some(message=>message.startsWith('New Reel sequence created.')));
});
test('review text bounds positions and preserves exact seconds, canvas, actual duration and music coverage',async()=>{
 const f=fixture(),reviewed=await f.review('reel',r=>{r.plan.summary.cuts=Array.from({length:80},(_,i)=>i+.123456);r.plan.summary.ranges=[];r.plan.summary.music_coverage=12.345678;});const lines=f.scope.recipeReviewLines(reviewed);assert.equal(lines.filter(line=>line.startsWith('Cut:')).length,50);assert.ok(lines.includes('30 more positions in the recipe review API response.'));assert.ok(lines.includes('Music coverage 12.345678 s'));assert.ok(lines.includes('Planned duration 14.500000 s'));assert.ok(lines.includes('Canvas 1080 × 1920 · 30 fps'));
});
test('ordered bin selection and source parent changes invalidate opening capture while preparation metadata does not',()=>{
 const f=fixture();f.project.media.n.subclip_of='parent';f.project.media.parent={...plain(f.project.media.n),id:'parent',subclip_of:null};const capture=f.scope.captureRecipeTargets('reel');f.project.media.n.proxy_status='ready';assert.equal(f.scope.recipeTargetsCurrent(capture),true);f.project.media.parent.path='/relinked';assert.equal(f.scope.recipeTargetsCurrent(capture),false);
 const g=fixture(),other=g.scope.captureRecipeTargets('reel');other.shots.reverse();assert.equal(g.scope.recipeTargetsCurrent(other),false);
});
test('Reel catalog failures never queue a recipe and retained callbacks cannot reuse a reopened dialog',async()=>{
 const f=fixture();delete f.scope.S.luts;const pending=f.open('reel');assert.equal(f.requests.length,1);f.reply(0,{detail:'Unavailable'},500);await pending;assert.equal(f.dialog('reel').button.disabled,true);assert.match(f.dialog('reel').output.textContent,/Unavailable/);assert.equal(f.requests.length,1);
 const g=fixture();g.open('talking_head');const callback=g.dialog('talking_head').button.onclick;g.open('talking_head');await callback();assert.equal(g.requests.length,0);
});
test('unlinked picture can open recipe controls for cosmetic changes but rejects audio treatment',async()=>{
 const f=fixture();f.tr.clips[0].audio.linked=false;f.open('talking_head');assert.equal(f.dialog('talking_head').box.classList.contains('open'),true);await f.dialog('talking_head').button.onclick();assert.equal(f.requests.length,0);assert.match(f.dialog('talking_head').output.textContent,/Relink picture audio/);f.scope.$('#thSilences').checked=false;f.scope.$('#thVoice').checked=false;f.dialog('talking_head').box.onchange();const pending=f.dialog('talking_head').button.onclick();await until(()=>f.requests.length===1);assert.equal(f.body().silences,false);assert.equal(f.body().voice_preset,false);f.dialog('talking_head').cancel.onclick();f.reply(0,f.queued());await pending;assert.equal(f.requests.length,1);
});

test('recipe review exposes exact bounded transitions and qualified numeric onset regularity',async()=>{
 const f=fixture(),reviewed=await f.review('reel',r=>{r.plan.summary.onset_count=3;r.plan.summary.tempo_confidence=.81234;r.plan.summary.transitions=Array.from({length:55},(_,i)=>({at:i+.123456,type:i%2?'dip_black':'dissolve',align:'center',duration:.066667}));});const lines=f.scope.recipeReviewLines(reviewed);assert.ok(lines.includes('Cuts placed on measured onsets: 3'));assert.ok(lines.includes('Onset regularity score: 0.812 / 1. This score does not establish musical structure or guarantee edit quality.'));assert.equal(lines.filter(line=>line.startsWith('Transition:')).length,50);assert.ok(lines.includes('Transition: 0.123456 s · dissolve · center · 0.066667 s'));assert.ok(lines.includes('Transition: 1.123456 s · dip_black · center · 0.066667 s'));assert.ok(lines.includes('5 more transitions in the recipe review API response.'));assert.ok(!lines.some(line=>line.includes('Detected onset candidates')));
});
